name: micro-service-infra-pipeline
trigger:
  branches:
    include:
      - main
pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: SASTScanning
  displayName: 'Static Application Security Testing (SAST) Scanning'
  jobs:
  - job: SASTScanning
    displayName: 'Run SAST Scan'
    steps:
    - task: cmdLine@2
      displayName: 'Trivy Vulnerability Scanner'
      inputs:
        targetType: 'inline'
        script: |
          echo "Running SAST scan..."
          trivy config . --format sarif -o trivy-result.xml
          echo "SAST scan completed."